server:
  port: 8080

spring:

    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:{web.upload-path}


    http:
      multipart:
                 max-file-size: 200mb
                 max-request-size: 200mb
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/lostAndFound?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

          username: root
          password: aa123456
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lostfound.pojo  # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

